apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-worker-22527
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-worker-22527
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
